const nestedQuestions = {
  Pressure: [
    { question: "Do you find studies a burden?" },
    { question: "Do you always try to maintain your important role among your friends?" },
    { question: "Do you feel behind time?" },
    { question: "Do you have to struggle to keep up with the pace of time?" },
    { question: "Are you a responsible child?" },
    { question: "Do you smoke or consume alcohol?" },
    { question: "Do you find it difficult to take quick decisions?" },
    { question: "Do you work under time pressure?" },
    { question: "Do your friends pressure you to behave like them often?" },
    { question: "Do you think your parents expect/expect more than you need?" },
    { question: "Do you feel boring to do the work you were happy to do earlier?" },
    { question: "Is there a mistake in spite of doing some work carefully?" },
  ],
  PhysicalStress: [
    { question: "Do you often have headaches?" },
    { question: "Do you often feel mentally or physically tired?" },
    { question: "After studying for a while, do your hands and feet start twitching?" },
    { question: "Do you not feel refreshed even after waking up in the morning?" },
  ],
  Anxiety: [
    { question: "Do you find your life boring?" },
    { question: "Do you fear being rejected by your friends?" },
    { question: "Do you not fall asleep for a long time even after going to sleep?" },
    { question: "Do you often remain worried?" },
    { question: "Is your performance declining in any work?" },
    { question: "Do you often feel guilty?" },
    { question: "Have you faced embarrassment many times?" },
    { question: "Do you feel helpless?" },
    { question: "Are you unable to concentrate on your work?" },
    { question: "Do you remain very worried about the future?" },
    { question: "Do you feel lack of concentration?" },
    { question: "Do you often have any confusion in your mind?" },
    { question: "Does your mind often remain unstable?" },
  ],
  Frustration: [
    { question: "Do you often feel irritable?" },
    { question: "Do you lose your temper quickly?" },
    { question: "Do failures discourage you quickly?" },
    { question: "Do you lose control during any kind of argument?" },
    { question: "Do you get angry often?" },
    { question: "Do you start shouting in anger?" },
    { question: "Do you find it intolerable to be interrupted repeatedly by your mother or father?" },
    { question: "Do you regret your life so far?" },
    { question: "Do you feel that your life is a failure?" },
  ],
};

module.exports = nestedQuestions;
